#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AzureAdMobile.Droid.Resource", IsApplication=true)]

namespace AzureAdMobile.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.Id.agentWebView = global::AzureAdMobile.Droid.Resource.Id.agentWebView;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.Layout.WebAuthenticationBroker = global::AzureAdMobile.Droid.Resource.Layout.WebAuthenticationBroker;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.String.ApplicationName = global::AzureAdMobile.Droid.Resource.String.ApplicationName;
			global::ModernHttpClient.Resource.String.library_name = global::AzureAdMobile.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int accessToken = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int accessTokenType = 2131034122;
			
			// aapt resource value: 0x7f050016
			public const int agentWebView = 2131034134;
			
			// aapt resource value: 0x7f050004
			public const int callBasic = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int callBasicGroup = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int callElevated = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int callElevatedGroup = 2131034117;
			
			// aapt resource value: 0x7f050014
			public const int compareTokens = 2131034132;
			
			// aapt resource value: 0x7f050008
			public const int console = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int consoleLayout = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int expiresOn = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int idToken = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int loginApp = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int loginBackend = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int logout = 2131034119;
			
			// aapt resource value: 0x7f050015
			public const int pager = 2131034133;
			
			// aapt resource value: 0x7f05000d
			public const int tenantId = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int title = 2131034112;
			
			// aapt resource value: 0x7f050010
			public const int userDisplayableId = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int userFamilyName = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int userGivenName = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int userIdentityProvider = 2131034131;
			
			// aapt resource value: 0x7f05000f
			public const int userUniqueId = 2131034127;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int backendData = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragmentLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int WebAuthenticationBroker = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int app_name = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int callBasic = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int callBasicGroup = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int callElevated = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int callElevatedGroup = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int compareTokens = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int loginApp = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int loginBackend = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int logout = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
